# Generated by Django 4.0.6 on 2022-07-31 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('canSeeMyAccount', 'Can see the my account page'), {'canSeeMyOrders', 'Can see the placed orders'}]},
        ),
    ]
