# Generated by Django 4.0.6 on 2022-08-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
